{{- if and .Values.server.enabled .Values.server.provisioning.enabled .Values.server.provisioning.files (not .Values.server.provisioning.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-provisioning" (include "authup.server.fullname" .) }}
  namespace: {{ include "authup.namespace" . | quote }}
  labels: {{- include "authup.labels" (dict "context" $ "component" "server") | nindent 4 }}
  annotations: {{- include "authup.annotations" (dict "context" $) | nindent 4 }}
data:
  {{- range $filename, $content := .Values.server.provisioning.files }}
  {{ $filename }}: |-
    {{- include "authup.tplvalues.render" (dict "value" $content "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
