{{- if .Values.mysql.enabled }}
{{- $secretName := include "authup.mysql.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "authup.namespace" . | quote }}
  labels: {{- include "authup.labels" (dict "context" $ "component" "mysql") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "authup.annotations" (dict "context" $) | nindent 4 }}
type: Opaque
data:
  password: {{ include "authup.secret.rawValue" (dict "secret" $secretName "key" "password" "value" .Values.mysql.auth.password "length" 32 "context" $) | b64enc | quote }}
  root-password: {{ include "authup.secret.rawValue" (dict "secret" $secretName "key" "root-password" "value" "" "length" 32 "context" $) | b64enc | quote }}
{{- end }}
