{{- if and .Values.smtp.connectionString (not .Values.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-smtp" (include "authup.fullname" .) }}
  namespace: {{ include "authup.namespace" . | quote }}
  labels: {{- include "authup.labels" (dict "context" $) | nindent 4 }}
  annotations: {{- include "authup.annotations" (dict "context" $) | nindent 4 }}
type: Opaque
data:
  smtp-connection-string: {{ .Values.smtp.connectionString | b64enc | quote }}
{{- end }}
