{{- if include "authup.auth.createSecret" . }}
{{- $secretName := include "authup.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "authup.namespace" . | quote }}
  labels: {{- include "authup.labels" (dict "context" $) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "authup.annotations" (dict "context" $) | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.adminPasswordKey }}: {{ include "authup.secret.rawValue" (dict "secret" $secretName "key" .Values.auth.secretKeys.adminPasswordKey "value" .Values.auth.adminPassword "length" 32 "context" $) | b64enc | quote }}
  {{- if .Values.auth.systemClientEnabled }}
  {{ .Values.auth.secretKeys.systemClientSecretKey }}: {{ include "authup.secret.rawValue" (dict "secret" $secretName "key" .Values.auth.secretKeys.systemClientSecretKey "value" .Values.auth.systemClientSecret "length" 32 "context" $) | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.secretsEncryptionKey }}
  {{ .Values.auth.secretKeys.secretsEncryptionKeyKey }}: {{ .Values.auth.secretsEncryptionKey | b64enc | quote }}
  {{- end }}
{{- end }}
