{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" (include "authup.ui.fullname" .) }}
  namespace: {{ include "authup.namespace" . | quote }}
  labels: {{- include "authup.labels" (dict "context" $ "component" "ui") | nindent 4 }}
  annotations: {{- include "authup.annotations" (dict "context" $) | nindent 4 }}
data: {{- include "authup.ui.configEnv" . | nindent 2 }}
{{- end }}
